<?php
$z[0]=Array("channel","\r\n      <dd><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n      ",174,334);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['noself']="yes";
$z[1]=Array("arclist","\r\n	  <li class=\"item\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n        <figure><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></figure>\r\n        <h3>[field:title/]</h3>\r\n        </a></li>\r\n		",429,709);
$z[1][4]=array();
$z[1][4]['row']="6";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",766,789);
$z[2][4]=array();
$z[2][4]['name']="id";

?>