<?php
$z[0]=Array("field","",90,118);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",161,192);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",232,261);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n		  <li><a>\r\n            <div class=\"img\"><img id=\"imgs\" src=\"[field:litpic/]\"/></div>\r\n            <div class=\"text\">\r\n              <h2>[field:title/]</h2>\r\n              <pre>[field:description function=\"cn_substr(@me,80)\"/]...</pre>\r\n            </div>\r\n            </a></li>\r\n			",371,745);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="3";
$z[3][4]['flag']="f";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";

?>