<?php
$z[0]=Array("field","",64,93);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","\r\n      <dd><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n      ",191,351);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n	  <li class=\"item\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n        <figure><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></figure>\r\n        <h3>[field:title/]</h3>\r\n        </a></li>\r\n		",446,726);
$z[2][4]=array();
$z[2][4]['row']="6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";
$z[3]=Array("field","",783,806);
$z[3][4]=array();
$z[3][4]['name']="id";

?>