
	<li><a href="[field:typelink/]">[field:typename/]</a></li>[field:global runphp='yes' name=autoindex]if(@me%8==1){
														@me='';
													}else if(@me%8==2){
														@me='';
													}else if(@me%8==3){@me='
	
	<li class="lh-logo"><a href="/"><img src="/skin/images/logo.png"/></a></li>';
													}else if(@me%8==4){
														@me='';
													}else if(@me%8==5){
														@me='';
													}else if(@me%8==6){
														@me='';
													}else if(@me%8==7){
														@me='';
													}else{
														@me='';
													}[/field:global]	
	