<?php
$z[0]=Array("global","",175,195);
$z[0][4]=array();
$z[0][4]['name']="cfg_g";
$z[1]=Array("field","",201,230);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",270,302);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("arclist","\r\n		<div class=\"floor_5_z\" aos=\"fade-right\" aos-easing=\"ease\" aos-duration=\"700\" aos-delay=\"100\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><b><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></b><em><span>[field:pubdate function=\"MyDate('d',@me)\"/]</span>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</em>\r\n          <div class=\"dk\">\r\n            <h3>[field:title/]</h3>\r\n            <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n            <i>查看详情</i></div>\r\n          </a></div>\r\n		  ",398,988);
$z[3][4]=array();
$z[3][4]['limit']="0,1";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><em><span>[field:pubdate function=\"MyDate('d',@me)\"/]</span>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</em>\r\n              <h3>\r\n                <p>[field:title/]<span>[field:description function=\"cn_substr(@me,300)\"/]...</span></p>\r\n              </h3>\r\n              </a></li>\r\n			  ",1158,1577);
$z[4][4]=array();
$z[4][4]['limit']="1,3";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";

?>