<li><a href="[field:arcurl/]" title="[field:title/]" class="iopo"><img class="bpic" src="[field:litpic/]" alt="[field:title/]"/></a>
                <div class="txt">
                  <h2>[field:title/]</h2>
                  <p>[field:description function="cn_substr(@me,200)"/]...</p>
                  <div class="lx"><a href="[field:arcurl/]" title="[field:title/]" title="[field:title/]" class="x1">查看详情</a><a href="http://wpa.qq.com/msgrd?v=3&uin=88888888&site=qq&menu=yes" title="立即咨询" class="x2">立即咨询</a></div>
                </div>
              </li>