<?php
$z[0]=Array("field","",11,37);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",61,89);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",98,127);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",129,158);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>",210,338);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>