{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/200121/1-2001211KI7.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-2001211KI7.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200121/1-2001211KI8.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-2001211KI8.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200121/1-2001211KJ0.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-2001211KJ0.jpg {/dede:img}
