<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/200121/1-2001211KI7.jpg ",93,236);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/200121/1-2001211KI7.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="440";
$z[1][4]['height']="330";
$z[2]=Array("img"," /uploads/allimg/200121/1-2001211KI8.jpg ",238,381);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/200121/1-2001211KI8.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="440";
$z[2][4]['height']="330";
$z[3]=Array("img"," /uploads/allimg/200121/1-2001211KJ0.jpg ",383,526);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/200121/1-2001211KJ0.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="440";
$z[3][4]['height']="330";

?>