<div class="floor_6_main">
  <div class="index_title" aos="fade-up" aos-easing="ease" aos-duration="700">
    <h3>{dede:field name='typename'/}</h3>
    <p></p>
  </div>
  <div class="floor_6">
    <div class="floor_5_1 w1200"> 
      <!--推荐内容开始--> 
      {dede:arclist limit='0,1' titlelen='50' orderby='pubdate'}
	  <div class="floor_5_z" aos="fade-right" aos-easing="ease" aos-duration="700" aos-delay="100"><a href="[field:arcurl/]" title="[field:title/]"><b><img src="[field:litpic/]" alt="[field:title/]"></b><em><span>[field:pubdate function="MyDate('d',@me)"/]</span>[field:pubdate function="MyDate('Y-m',@me)"/]</em>
        <div class="dk">
          <h3>[field:title/]</h3>
          <p>[field:description function="cn_substr(@me,200)"/]...</p>
          <i>查看详情</i></div>
        </a></div>
		{/dede:arclist}
 
      <!--推荐内容结束-->
      <div class="floor_5_y" aos="fade-left" aos-easing="ease" aos-duration="700" aos-delay="100">
        <ul>
          <li><a href="/a/xinwenzhongxin/changjianwenti/36.html" title="站在用户的角度思考什么是运营"><em><span>29</span>2019-10</em>
            <h3>
              <p>站在用户的角度思考什么是运营<span>每个人的对于运营的理解会不一样，运营这个群体中有很大一部分人是误打误撞进入这个圈的，不同的项目、业务、负责不同的模块，360行的运营会产生...</span></p>
            </h3>
            </a></li>
<li><a href="/a/xinwenzhongxin/changjianwenti/35.html" title="如何让访客接受你的网站呢"><em><span>29</span>2019-10</em>
            <h3>
              <p>如何让访客接受你的网站呢<span>也许你已经给网站优化了一段时间，但是放心好像网站一点效果都没有，也许你会很气馁，失去信心，那么我们应该这么样去做找到问题的原因呢？ ①增加...</span></p>
            </h3>
            </a></li>
<li><a href="/a/xinwenzhongxin/changjianwenti/34.html" title="怎么样检查和优化网站的速度"><em><span>29</span>2019-10</em>
            <h3>
              <p>怎么样检查和优化网站的速度<span>网站的打开速度是一个比较重要的因素，对于任何一个网站来说打开的速度跟用户的跳出率，以及网站的优化工作都是有直接的关系，在优化过程中你也可...</span></p>
            </h3>
            </a></li>

        </ul>
      </div>
    </div>
  </div>
</div>