{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/200204/1-200204123F1.jpg' text='' width='440' height='330'} /uploads/allimg/200204/1-200204123F1.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200204/1-200204123F3.jpg' text='' width='440' height='330'} /uploads/allimg/200204/1-200204123F3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200204/1-200204123F5.jpg' text='' width='440' height='330'} /uploads/allimg/200204/1-200204123F5.jpg {/dede:img}
