<?php
$z[0]=Array("global","",117,137);
$z[0][4]=array();
$z[0][4]['name']="cfg_g";
$z[1]=Array("field","",143,172);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",197,229);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("arclist","<dl class=\"\">\r\n          <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n          <dt><img src=\"[field:litpic/]\"  alt=\"[field:title/]\"></dt>\r\n          <dd><i></i>\r\n            <h3>[field:title/]<span></span></h3>\r\n            <p>[field:description function=\"cn_substr(@me,80)\"/]...</p>\r\n          </dd>\r\n          </a>\r\n        </dl>\r\n		",271,691);
$z[3][4]=array();
$z[3][4]['row']="4";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",757,780);
$z[4][4]=array();
$z[4][4]['name']="id";

?>