<?php
$z[0]=Array("field","",131,160);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",185,217);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]\r\n        ",316,466);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("field","",532,555);
$z[3][4]=array();
$z[3][4]['name']="id";

?>