<?php
$z[0]=Array("field","",102,131);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",154,186);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n          <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",357,525);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("arclist","\r\n			<li class=\"item\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n              <figure><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></figure>\r\n              <h3>[field:title/]</h3>\r\n              </a></li>\r\n			  ",708,1010);
$z[3][4]=array();
$z[3][4]['row']="6";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",1114,1137);
$z[4][4]=array();
$z[4][4]['name']="id";

?>