<?php
$z[0]=Array("field","",64,93);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","<div class=\"swiper-slide\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n          <div class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></div>\r\n          <h3>[field:title/]</h3>\r\n          </a></div>\r\n		  ",198,497);
$z[1][4]=array();
$z[1][4]['row']="6";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("field","",609,632);
$z[2][4]=array();
$z[2][4]['name']="id";

?>