<?php
$z[0]=Array("field","",116,145);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n	  <div class=\"floor_5_z\" aos=\"fade-right\" aos-easing=\"ease\" aos-duration=\"700\" aos-delay=\"100\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><b><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></b><em><span>[field:pubdate function=\"MyDate('d',@me)\"/]</span>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</em>\r\n        <div class=\"dk\">\r\n          <h3>[field:title/]</h3>\r\n          <p>[field:description function=\"cn_substr(@me,180)\"/]...</p>\r\n          <i>查看详情</i></div>\r\n        </a></div>\r\n		",276,855);
$z[1][4]=array();
$z[1][4]['limit']="0,1";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("arclist","\r\n		  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><em><span>[field:pubdate function=\"MyDate('d',@me)\"/]</span>[field:pubdate function=\"MyDate('Y-m',@me)\"/]</em>\r\n            <h3>\r\n              <p>[field:title/]<span>[field:description function=\"cn_substr(@me,180)\"/]...</span></p>\r\n            </h3>\r\n            </a></li>\r\n			",1017,1427);
$z[2][4]=array();
$z[2][4]['limit']="1,3";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>