<?php
$z[0]=Array("field","",213,242);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",266,298);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("channel","\r\n			  <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n			  ",439,564);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";
$z[3]=Array("arclist","\r\n			  <li data-url=\"[field:arcurl/]\"> <img src=\"[field:litpic/]\"/> </li>\r\n			  ",713,862);
$z[3][4]=array();
$z[3][4]['row']="3";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\">\r\n                <h2>[field:title/]</h2>\r\n                <pre>[field:description function=\"cn_substr(@me,200)\"/]...</pre>\r\n                <div class=\"time clearfix\">\r\n                  <h3 class=\"left\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</h3>\r\n                  <h4 class=\"right\">查看详情</h4>\r\n                </div>\r\n                </a></li>\r\n				",934,1409);
$z[4][4]=array();
$z[4][4]['row']="3";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";

?>