<?php
$z[0]=Array("field","",185,214);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",254,286);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("arclist","<dl class=\"dl[field:global.autoindex/]\" aos=\"fade-right\" aos-easing=\"ease\" aos-duration=\"700\" aos-delay=\"100\">\r\n          <a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n          <dt><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></dt>\r\n          <dd><i></i>\r\n            <h3>[field:title/]<span></span></h3>\r\n            <p>[field:description function=\"cn_substr(@me,150)\"/]...</p>\r\n          </dd>\r\n          </a>\r\n        </dl>\r\n		",336,844);
$z[2][4]=array();
$z[2][4]['row']="4";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>