<dl class="dl[field:global.autoindex/]" aos="fade-right" aos-easing="ease" aos-duration="700" aos-delay="100">
          <a href="[field:arcurl/]" title="[field:title/]">
          <dt><img src="[field:litpic/]" alt="[field:title/]"></dt>
          <dd><i></i>
            <h3>[field:title/]<span></span></h3>
            <p>[field:description function="cn_substr(@me,200)"/]...</p>
          </dd>
          </a>
        </dl>