<?php
$z[0]=Array("global","",113,133);
$z[0][4]=array();
$z[0][4]['name']="cfg_g";
$z[1]=Array("field","",139,168);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",193,225);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]\r\n        ",324,474);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";
$z[4]=Array("field","",540,563);
$z[4][4]=array();
$z[4][4]['name']="id";

?>