<?php
$z[0]=Array("field","",111,140);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n		<li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n          <div class=\"con\">\r\n            <h3>[field:title/]</h3>\r\n            <span></span>\r\n            <p>[field:description function=\"cn_substr(@me,120)\"/]...</p>\r\n          </div>\r\n          </a></li>\r\n		  ",333,720);
$z[1][4]=array();
$z[1][4]['row']="10";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";

?>