<?php
$z[0]=Array("field","",321,350);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",392,424);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("field","",567,596);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]\r\n        ",619,769);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";
$z[4]=Array("field","",799,827);
$z[4][4]=array();
$z[4][4]['name']="typeurl";
$z[5]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",1133,1254);
$z[5][4]=array();
$z[5][4]['typeid']="3";
$z[6]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",1269,1390);
$z[6][4]=array();
$z[6][4]['typeid']="4";
$z[7]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n                <p>[field:title/]</p>\r\n                </a></li>\r\n				",1660,1921);
$z[7][4]=array();
$z[7][4]['typeid']="3";
$z[7][4]['row']="10";
$z[7][4]['titlelen']="50";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n                <p>[field:title/]</p>\r\n                </a></li>\r\n				",2174,2435);
$z[8][4]=array();
$z[8][4]['typeid']="4";
$z[8][4]['row']="10";
$z[8][4]['titlelen']="50";
$z[8][4]['orderby']="pubdate";

?>