<?php
$z[0]=Array("field","",112,140);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",214,243);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("sql"," \r\n        [field:content/]\r\n        ",265,374);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=34";
$z[3]=Array("channel","\r\n			<li><a href=\"[field:typelink/]\">\r\n              <div class=\"img\"><img src=\"[field:typeimg/]\" /></div>\r\n              <h4>[field:typename/]</h4>\r\n              </a></li>\r\n			  ",451,684);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>