<?php
$z[0]=Array("global","@me=@me+8;",29,96);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[0][4]['runphp']="yes";
$z[1]=Array("global","\r\n                      \$a=\"\";\r\n                        \$b=\"class='on'\";\r\n                        if ((@me%1)==0 && @me!=1)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",96,350);
$z[1][4]=array();
$z[1][4]['runphp']="yes";
$z[1][4]['name']="autoindex";
$z[2]=Array("typename","",352,369);
$z[2][4]=array();

?>