<?php
$z[0]=Array("typelink","",16,33);
$z[0][4]=array();
$z[1]=Array("typename","",35,52);
$z[1][4]=array();
$z[2]=Array("global","if(@me==1)@me=\"\";elseif(@me==14)@me=\"<li class='lh-logo'><a href='/'><img src='/skin/images/logo.png'/></a></li>\";else @me=\"\";",64,247);
$z[2][4]=array();
$z[2][4]['name']="autoindex";
$z[2][4]['runphp']="yes";
$z[3]=Array("global","\r\n                      \$a=\"\r\n	<li class=\"lh-logo\"><a href='/'><img src='/skin/images/logo.png'/></a></li>\";\r\n                        \$b=\"\";\r\n                        if ((@me%6)==3 && @me!=5)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",250,572);
$z[3][4]=array();
$z[3][4]['runphp']="yes";
$z[3][4]['name']="autoindex";

?>