
      <li>
        <div class="img" style="background-image:url([field:typeimg/]);"></div>
        <div class="text wow animated fadeInUp">
          <div>
            <h2 class="lh-public-h2">[field:typenameen/]</h2>
            <h3 class="lh-public-h3">[field:typename/]</h3>
            <pre class="lh-public-pre">[field:description/]...</pre>
            <a href="[field:typelink/]" class="lh-look">查看更多</a> </div>
        </div>
      </li>
      