<div class="floor_6_main">
    <div class="w1200 clearfix"> 
      <!--公司简介开始-->
      <div class="floor_6_1" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">
        <div class="indexTit" aos="fade-up" aos-easing="ease" aos-duration="700">
          <h3 class="tit">某某公司<span>{dede:field name='typename'/}</span></h3>
          <p class="subtit">{dede:field name='description'/}</p>
        </div>
        <div class="floor_6_2"> <b></b><img src="/skin/images/about.jpg"/>
          <div class="f_z">
            <h3>{dede:field name='typename'/}</h3>
            <p> {dede:sql sql='Select content from dede_arctype where id=1'} 
        [field:content  function='cn_substr(html2text(@me),400)'/]
        {/dede:sql}...</p>
            <a href="/a/guanyuwomen/">查看详情</a></div>
        </div>
      </div>
      <!--公司简介结束--> 
      <!--厂房展示-荣誉资质开始-->
      <div class="floor_6_3">
        <div class="parHd" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="100"> <s></s><b></b>
          <ul>
            <li><a href="/a/guanyuwomen/changfang/" title="厂房展示">厂房展示</a></li> 
            <li><a href="/a/guanyuwomen/gongsizizhi/" title="公司资质">公司资质</a></li>
          </ul>
        </div>
        <div class="parBd" aos="fade-up" aos-easing="ease" aos-duration="700" aos-delay="200">
          <div class="slideBox"><a class="sPrev" href="javascript:void(0)"><span class="icon"></span></a>
            <ul>
              <li><a href="/a/guanyuwomen/changfang/49.html" title="企业风采标题六"><img src="/uploads/allimg/191029/1-19102915435G23.jpg" alt="企业风采标题六">
                <p>企业风采标题六</p>
                </a></li>
<li><a href="/a/guanyuwomen/changfang/48.html" title="企业风采标题五"><img src="/uploads/allimg/191029/1-19102915433G35.jpg" alt="企业风采标题五">
                <p>企业风采标题五</p>
                </a></li>
<li><a href="/a/guanyuwomen/changfang/47.html" title="企业风采标题四"><img src="/uploads/allimg/191029/1-19102915431B25.jpg" alt="企业风采标题四">
                <p>企业风采标题四</p>
                </a></li>
<li><a href="/a/guanyuwomen/changfang/46.html" title="企业风采标题三"><img src="/uploads/allimg/191029/1-191029154255610.jpg" alt="企业风采标题三">
                <p>企业风采标题三</p>
                </a></li>
<li><a href="/a/guanyuwomen/changfang/45.html" title="企业风采标题二"><img src="/uploads/allimg/191029/1-191029154235T5.jpg" alt="企业风采标题二">
                <p>企业风采标题二</p>
                </a></li>
<li><a href="/a/guanyuwomen/changfang/44.html" title="企业风采标题一"><img src="/uploads/allimg/191029/1-191029154213426.jpg" alt="企业风采标题一">
                <p>企业风采标题一</p>
                </a></li>

            </ul>
            <a class="sNext" href="javascript:void(0)"><span class="icon"></span></a></div>
          <div class="slideBox"><a class="sPrev" href="javascript:void(0)"><span class="icon"></span></a>
            <ul>
              <li><a href="/a/guanyuwomen/gongsizizhi/43.html" title="荣誉资质标题六"><img src="/uploads/allimg/191029/1-1910291541262G.jpg" alt="荣誉资质标题六">
                <p>荣誉资质标题六</p>
                </a></li>
<li><a href="/a/guanyuwomen/gongsizizhi/42.html" title="荣誉资质标题五"><img src="/uploads/allimg/191029/1-191029154105527.jpg" alt="荣誉资质标题五">
                <p>荣誉资质标题五</p>
                </a></li>
<li><a href="/a/guanyuwomen/gongsizizhi/41.html" title="荣誉资质标题四"><img src="/uploads/allimg/191029/1-191029154033603.jpg" alt="荣誉资质标题四">
                <p>荣誉资质标题四</p>
                </a></li>
<li><a href="/a/guanyuwomen/gongsizizhi/40.html" title="荣誉资质标题三"><img src="/uploads/allimg/191029/1-191029154010K3.jpg" alt="荣誉资质标题三">
                <p>荣誉资质标题三</p>
                </a></li>
<li><a href="/a/guanyuwomen/gongsizizhi/39.html" title="荣誉资质标题二"><img src="/uploads/allimg/191029/1-19102915394R42.jpg" alt="荣誉资质标题二">
                <p>荣誉资质标题二</p>
                </a></li>
<li><a href="/a/guanyuwomen/gongsizizhi/38.html" title="荣誉资质标题一"><img src="/uploads/allimg/191029/1-191029153923b5.jpg" alt="荣誉资质标题一">
                <p>荣誉资质标题一</p>
                </a></li>

            </ul>
            <a class="sNext" href="javascript:void(0)"><span class="icon"></span></a></div>
        </div>
      </div>
      <!--厂房展示-荣誉资质结束--> 
    </div>
  </div>