<?php
$z[0]=Array("field","",321,350);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",392,424);
$z[1][4]=array();
$z[1][4]['name']="description";
$z[2]=Array("field","",567,596);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),400)'/]\r\n        ",619,769);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";

?>