<?php
$z[0]=Array("typelink","",13,30);
$z[0][4]=array();
$z[1]=Array("typename","",32,49);
$z[1][4]=array();
$z[2]=Array("global","if(@me%8==1){\r\n														@me='';\r\n													}else if(@me%8==2){\r\n														@me='';\r\n													}else if(@me%8==3){@me='\r\n	<li class=\"lh-logo\"><a href=\"/\"><img src=\"/skin/images/logo.png\"/></a></li>\r\n	';\r\n													}else if(@me%8==4){\r\n														@me='';\r\n													}else if(@me%8==5){\r\n														@me='';\r\n													}else if(@me%8==6){\r\n														@me='';\r\n													}else if(@me%8==7){\r\n														@me='';\r\n													}else{\r\n														@me='';\r\n													}",58,618);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[2][4]['name']="autoindex";

?>