<div class="lh-profile clearfix" id="about9">
      <div class="img" style="background-image:url({dede:field name='typeimg'/});"><a href='javascript:;' class="lh-video-btn"><i class="iconfont icon-bofang"></i></a></div>
      <div class="text">
        <div>
          <h2 class="lh-public-h2">Into Bestpostal</h2>
          <h3 class="lh-public-h3">某某邮政专用设备制造有限公司</h3>
          <pre class="lh-public-pre">{dede:sql sql='Select content from dede_arctype where id=2'} 
        [field:content/]
        {/dede:sql}</pre>
          <a href="#" class="lh-look">查看更多</a> </div>
      </div>
    </div>