<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/200219/1-200219102005.jpg ",93,240);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/200219/1-200219102005.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="600";
$z[1][4]['height']="600";
$z[2]=Array("img"," /uploads/allimg/200219/1-200219102006.png ",242,389);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/200219/1-200219102006.png";
$z[2][4]['text']="";
$z[2][4]['width']="600";
$z[2][4]['height']="600";

?>