<?php
$z[0]=Array("field","",179,208);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img class=\"img\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                <div class=\"txt\">\r\n                  <h3>[field:title/]</h3>\r\n                  <p>[field:description function=\"cn_substr(@me,150)\"/]...</p>\r\n                </div>\r\n                </a></li>\r\n				",498,903);
$z[1][4]=array();
$z[1][4]['row']="4";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";

?>