<div class="floor_5_main">
    <div class="floor_5 w1200 clearfix">
      <div class="indexTit" aos="fade-up" aos-easing="ease" aos-duration="700">
        <h3 class="tit"><em>{dede:field name='typename'/}</em></h3>
        <p class="subtit"></p>
      </div>
      <div class="cont clearfix"> 
        <!--推荐内容开始-->
        <div id="newsBox" class="newsBox fl" aos="fade-right" aos-easing="ease" aos-duration="700">
          <div class="bd">
            <ul>
              {dede:arclist row='4' titlelen='50' orderby='pubdate'}
			  <li><a href="[field:arcurl/]" title="[field:title/]"><img class="img" src="[field:litpic/]" alt="[field:title/]"/>
                <div class="txt">
                  <h3>[field:title/]</h3>
                  <p>[field:description function="cn_substr(@me,150)"/]...</p>
                </div>
                </a></li>
				{/dede:arclist}
            </ul>
          </div>
          <div class="hd">
            <ul>
            </ul>
          </div>
        </div>
        <!--推荐内容结束-->
        <div class="textlist fr" aos="fade-left" aos-easing="ease" aos-duration="700">
          <ul class="list">
            <li class="item"><a href="/a/xinwenzhongxin/changjianwenti/33.html" title="如何检查和优化网站的速度">
              <div class="time fl"><b>29</b>2019-10</div>
              <h3>如何检查和优化网站的速度</h3>
              <p>网站的打开速度是一个比较重要的因素，对于任何一个网站来说打开的速度跟用户的跳出率，以及网站的优化工作都是有直接的关系，在优化过程中你也可以看到一半打开速度慢的网站...</p>
              </a></li>
<li class="item"><a href="/a/xinwenzhongxin/changjianwenti/32.html" title="排名不提升 要怎么去优化">
              <div class="time fl"><b>29</b>2019-10</div>
              <h3>排名不提升 要怎么去优化</h3>
              <p>相信大家在接手网站优化的时候，经常会出现目标关键词排名不能够提升的情况，但是又不能确定是哪里出了问题。下面，小编就给大家介绍常见的优化分析方法，供大家参考学习！...</p>
              </a></li>
<li class="item"><a href="/a/xinwenzhongxin/xingyedongtai/31.html" title="浅析导致企业营销型网站效果差的几大原">
              <div class="time fl"><b>29</b>2019-10</div>
              <h3>浅析导致企业营销型网站效果差的几大原</h3>
              <p>相信不少企业都深有感触，那就是自己花费不菲的代价进行营销型网站建设以后，却总是事与愿违，迟迟不能产生效果，令企业不甚苦恼。站在企业的角度来说，一旦网站没有效果，也...</p>
              </a></li>

          </ul>
        </div>
      </div>
      <a href="/a/xinwenzhongxin/" class="more" aos="fade-up" aos-easing="ease" aos-duration="700">更多资讯 >></a> </div>
  </div>