<?php
$z[0]=Array("field","",63,94);
$z[0][4]=array();
$z[0][4]['name']="typenameen";
$z[1]=Array("field","",132,161);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",201,229);
$z[2][4]=array();
$z[2][4]['name']="content";
$z[3]=Array("arclist","\r\n		<li><a>\r\n          <div class=\"img\"><img src=\"[field:litpic/]\"/></div>\r\n          <h2>[field:shorttitle/]</h2>\r\n          <h3>[field:title/]</h3>\r\n          </a> </li>\r\n		  ",297,561);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="4";
$z[3][4]['flag']="";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";

?>