{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/200121/1-2001211KP0.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-2001211KP0.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200121/1-2001211KP2.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-2001211KP2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200121/1-2001211KP3.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-2001211KP3.jpg {/dede:img}
