
        <li><a href="/a/zoujinwomen/gongsijianjie/#about[field:global name=autoindex runphp="yes"]@me=@me+9;[/field:global]"[field:global runphp='yes' name=autoindex]
                      $a="";
                        $b="class='on'";
                        if ((@me%1)==0 && @me!=1)  @me=$a;
                        else  @me=$b;
                        [/field:global]>[field:typename/]</a></li>
        