{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/200121/1-200121111A2.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-200121111A2.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200121/1-200121111A4.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-200121111A4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/200121/1-200121111A6.jpg' text='' width='440' height='330'} /uploads/allimg/200121/1-200121111A6.jpg {/dede:img}
