<?php
$z[0]=Array("global","",84,104);
$z[0][4]=array();
$z[0][4]['name']="cfg_g";
$z[1]=Array("field","",110,139);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",162,194);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("channel","\r\n          <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n          ",365,533);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("arclist","\r\n			<li class=\"item\"><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n              <figure><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></figure>\r\n              <h3>[field:title/]</h3>\r\n              </a></li>\r\n			  ",716,1018);
$z[4][4]=array();
$z[4][4]['row']="6";
$z[4][4]['titlelen']="50";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("field","",1122,1145);
$z[5][4]=array();
$z[5][4]['name']="id";

?>