<?php
$z[0]=Array("typelink","",16,33);
$z[0][4]=array();
$z[1]=Array("typename","",35,52);
$z[1][4]=array();
$z[2]=Array("global","\r\n                      \$a=\"<li class='lh-logo'><a href='/'><img src='/skin/images/logo.png'/></a></li>\";\r\n                        \$b=\"\";\r\n                        if ((@me%6)==3 && @me!=5)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",64,383);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[2][4]['name']="autoindex";

?>