<?php
$z[0]=Array("field","",185,214);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",254,283);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",491,523);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",558,723);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";
$z[4]=Array("global","",821,843);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("field","",1071,1100);
$z[5][4]=array();
$z[5][4]['name']="typename";
$z[6]=Array("field","",1127,1155);
$z[6][4]=array();
$z[6][4]['name']="typeurl";
$z[7]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"iopo\"><img class=\"bpic\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a>\r\n                <div class=\"txt\">\r\n                  <h2>[field:title/]</h2>\r\n                  <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n                  <div class=\"lx\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" title=\"[field:title/]\" class=\"x1\">查看详情</a><a href=\"http://wpa.qq.com/msgrd?v=3&uin=88888888&site=qq&menu=yes\" title=\"立即咨询\" class=\"x2\">立即咨询</a></div>\r\n                </div>\r\n              </li>\r\n			  ",1283,1959);
$z[7][4]=array();
$z[7][4]['row']="10";
$z[7][4]['titlelen']="50";
$z[7][4]['orderby']="pubdate";
$z[8]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                    <h2>[field:title/]<i class=\"icon\"></i></h2>\r\n                    </a></li>\r\n					",2181,2464);
$z[8][4]=array();
$z[8][4]['row']="10";
$z[8][4]['titlelen']="50";
$z[8][4]['orderby']="pubdate";

?>