<?php
$z[0]=Array("field","",232,261);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n			<li><a href=\"[field:arcurl/]\">\r\n              <div class=\"img\"><img src=\"/skin/images/a[field:global.autoindex/].jpg\" /></div>\r\n              <div class=\"text\">\r\n                <h2>[field:title/]</h2>\r\n                <pre>[field:description function=\"cn_substr(@me,80)\"/]...</pre>\r\n                <h3>see more +</h3>\r\n              </div>\r\n              </a></li>\r\n			  ",418,865);
$z[1][4]=array();
$z[1][4]['row']="6";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";

?>