<?php
$z[0]=Array("field","",58,86);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",111,140);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",166,194);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",294,323);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("arclist","\r\n				<li> <a href=\"[field:arcurl/]\">\r\n                  <div class=\"img\"><img src=\"[field:litpic/]\"/></div>\r\n                  <div class=\"text\">[field:title/]</div>\r\n                  </a> </li>\r\n				  ",408,691);
$z[4][4]=array();
$z[4][4]['typeid']="";
$z[4][4]['row']="5";
$z[4][4]['titlelen']="60";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("field","",722,750);
$z[5][4]=array();
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",816,844);
$z[6][4]=array();
$z[6][4]['name']="typeurl";

?>