<?php
$z[0]=Array("field","",73,102);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\r\n		<li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n          <div class=\"tl\"><em>[field:title/]</em>\r\n            <p>[field:description function=\"cn_substr(@me,80)\"/]...</p>\r\n            <i>[field:pubdate function=\"MyDate('y-m-d',@me)\"/]</i></div>\r\n          </a></li>\r\n		  ",197,605);
$z[1][4]=array();
$z[1][4]['row']="5";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";

?>