<div class="lh-profile clearfix" id="about9">
      <div class="img" style="background-image:url({dede:field name='typeimg'/});"><a href='javascript:;' class="lh-video-btn"><i class="iconfont icon-bofang"></i></a></div>
      <div class="text">
        <div>
          {dede:sql sql='Select content from dede_arctype where id=2'} 
        [field:content/]
        {/dede:sql}
          <a href="#" class="lh-look">查看更多</a> </div>
      </div>
    </div>