<?php
$z[0]=Array("global","",84,104);
$z[0][4]=array();
$z[0][4]['name']="cfg_g";
$z[1]=Array("field","",110,139);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",162,194);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("arclist","\r\n		<li><a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n          <div class=\"tl\"><em >[field:title/]</em>\r\n            <p>[field:description function=\"cn_substr(@me,80)\"/]...</p>\r\n            <span>阅读数：[field:click/]</span><i>日期：[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</i></div>\r\n          </a></li>\r\n		  ",267,734);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="5";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("field","",814,837);
$z[4][4]=array();
$z[4][4]['name']="id";

?>