<?php
$z[0]=Array("arclist","\r\n			  <dd class=\"d[field:global.autoindex/]\">\r\n                <div class=\"box1\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                  <h3>[field:title/]</h3>\r\n                  <p>[field:description function=\"cn_substr(@me,180)\"/]...</p>\r\n                  <i class=\"icon\"></i><span class=\"icon\"></span></a></div>\r\n                <div class=\"box2\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a></div>\r\n              </dd>\r\n			  ",131,705);
$z[0][4]=array();
$z[0][4]['limit']="0,2";
$z[0][4]['titlelen']="50";
$z[0][4]['orderby']="pubdate";
$z[1]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                    <h3>[field:title/]</h3>\r\n                    </a></li>\r\n					",937,1203);
$z[1][4]=array();
$z[1][4]['limit']="2,6";
$z[1][4]['titlelen']="50";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("arclist","\r\n				  <li></li>\r\n				  ",1325,1423);
$z[2][4]=array();
$z[2][4]['limit']="2,6";
$z[2][4]['titlelen']="50";
$z[2][4]['orderby']="pubdate";

?>