<li class="swiper-slide style1"> <a href="[field:url/]">
            <div class="img" style="background-image:url([field:pic/]);"></div>
            <div class="text">
              <h2 data-swiper-parallax="-1500">[field:title/]</h2>
              <h3 data-swiper-parallax="-3000">[field:introduce/]</h3>
              <pre data-swiper-parallax="-4500"></pre>
            </div>
            </a> </li>