<?php
$z[0]=Array("arcurl","",26,41);
$z[0][4]=array();
$z[1]=Array("title","",50,64);
$z[1][4]=array();
$z[2]=Array("pubdate","",106,149);
$z[2][4]=array();
$z[2][4]['function']="MyDate('d',@me)";
$z[3]=Array("pubdate","",153,198);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y-m',@me)";
$z[4]=Array("title","",224,238);
$z[4][4]=array();
$z[5]=Array("description","",262,312);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,300)";

?>