<?php
$z[0]=Array("field","",13,41);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",50,79);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",88,114);
$z[2][4]=array();
$z[2][4]['name']="currentstyle";
$z[3]=Array("field","",131,160);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n            <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n            ",217,382);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>