<div class="lh-solut clearfix">
          <div class="img" style="background-image:url([field:litpic/]);"></div>
          <div class="lh-solut-text">
            <div> <i class="iconfont icon-a1"></i>
              <h2>[field:title/]</h2>
              <pre>[field:description function="cn_substr(@me,300)"/]...</pre>
              <a href="[field:arcurl/]" class="lh-look">查看更多</a> </div>
          </div>
        </div>