<?php
$z[0]=Array("field","",52,80);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",154,185);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",225,254);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\r\n			  <li class=\"swiper-slide\">\r\n                <h2>[field:shorttitle/]</h2>\r\n                <div class=\"cont clearfix\">\r\n                  <p><strong>[field:title/]</strong></p>\r\n                  <p><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"280\" height=\"210\" border=\"0\" vspace=\"0\" style=\"width: 280px; height: 210px;\"/></p>\r\n                </div>\r\n              </li>\r\n			  ",395,899);
$z[3][4]=array();
$z[3][4]['typeid']="";
$z[3][4]['row']="10";
$z[3][4]['flag']="";
$z[3][4]['titlelen']="60";
$z[3][4]['orderby']="pubdate";

?>