<?php
$z[0]=Array("typelink","",16,33);
$z[0][4]=array();
$z[1]=Array("typename","",35,52);
$z[1][4]=array();
$z[2]=Array("global","\r\n													if(@me%8==1){\r\n														@me='';\r\n													}else if(@me%8==2){\r\n														@me='';\r\n													}\r\n													else if(@me%8==3){\r\n														@me='';\r\n													}else if(@me%8==4){\r\n														@me='<li class='lh-logo'><a href='/'><img src='/skin/images/logo.png'/></a></li>';\r\n													}else if(@me%8==5){\r\n														@me='';\r\n													}else if(@me%8==6){\r\n														@me='';\r\n													}else if(@me%8==7){\r\n														@me='';\r\n													}else{\r\n														@me='';\r\n													}\r\n												",64,678);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[2][4]['name']="autoindex";
$z[3]=Array("typelink","",1403,1420);
$z[3][4]=array();
$z[4]=Array("typename","",1422,1439);
$z[4][4]=array();

?>