<?php
$z[0]=Array("field","",54,80);
$z[0][4]=array();
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",88,116);
$z[1][4]=array();
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",125,154);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",156,185);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","<a class=\"subA\" href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>  ",222,365);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>