<div class="swiper-slide" data-hash="About">
      <div class="lh-index-about">
        <div class="container clearfix">
          <div class="text">
            <h2>Into Bestpostal</h2>
            <h3>某某邮政专用设备制造有限公司</h3>
            <pre>某某邮政专用设备制造有限公司始创于1998年，<br />
是集研发、设计、生产、 销售、安装、服务为一体的国家高新技术企业，<br />
是智能快递柜、智能信报箱、 智能化邮件处理输送设备、智能化物流输送设备<br />
、智能化营业厅设备、智能 化亭体、智能化办公家具等智能化设备的专业生产厂家...</pre>
            <a href="{dede:field name='typeurl'/}" class="lh-more gray"></a> </div>
          <div class="img"> <img src="{dede:field name='typeimg'/}" /> <a href='javascript:;' class="lh-video-btn"><i class="iconfont icon-bofang"></i></a> </div>
        </div>
      </div>
    </div>