<?php
$z[0]=Array("global","",303,323);
$z[0][4]=array();
$z[0][4]['name']="cfg_g";
$z[1]=Array("field","",329,358);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",400,432);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("field","",575,604);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]\r\n        ",627,777);
$z[4][4]=array();
$z[4][4]['sql']="Select content from dede_arctype where id=1";
$z[5]=Array("field","",807,835);
$z[5][4]=array();
$z[5][4]['name']="typeurl";
$z[6]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",1141,1262);
$z[6][4]=array();
$z[6][4]['typeid']="3";
$z[7]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",1277,1398);
$z[7][4]=array();
$z[7][4]['typeid']="4";
$z[8]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n                <p>[field:title/]</p>\r\n                </a></li>\r\n				",1668,1929);
$z[8][4]=array();
$z[8][4]['typeid']="3";
$z[8][4]['row']="10";
$z[8][4]['titlelen']="50";
$z[8][4]['orderby']="pubdate";
$z[9]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n                <p>[field:title/]</p>\r\n                </a></li>\r\n				",2182,2443);
$z[9][4]=array();
$z[9][4]['typeid']="4";
$z[9][4]['row']="10";
$z[9][4]['titlelen']="50";
$z[9][4]['orderby']="pubdate";

?>