<div class="floor_5_z" aos="fade-right" aos-easing="ease" aos-duration="700" aos-delay="100"><a href="[field:arcurl/]" title="[field:title/]"><b><img src="[field:litpic/]" alt="[field:title/]"></b><em><span>[field:pubdate function="MyDate('d',@me)"/]</span>[field:pubdate function="MyDate('Y-m',@me)"/]</em>
        <div class="dk">
          <h3>[field:title/]</h3>
          <p>[field:description function="cn_substr(@me,200)"/]...</p>
          <i>查看详情</i></div>
        </a></div>