<div class="lh-profile honor clearfix" id="about10">
      <div class="img" style="background-image:url([field:typeimg /]);"></div>
      <div class="text">
        <div> <h2 class="lh-public-h2">[field:typenameen /]</h2>
          <h3 class="lh-public-h3">[field:typename /]</h3>
          <pre class="lh-public-pre">
[field:content /]
</pre>
          <a href="[field:typeimg /]" class="lh-look">查看更多</a> </div>
      </div>
    </div>