<?php
$z[0]=Array("field","",138,166);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",272,303);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",326,355);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",379,411);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[4]=Array("field","",461,489);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>