<div class="swiper-slide" data-hash="Rd">
      <div class="lh-index-rd clearfix">
        <div class="img" style="background-image:url({dede:field name='typeimg'/});"></div>
        <div class="container clearfix">
          <div class="text right">
            <h2>{dede:field name='typenameen'/}</h2>
            <h3>{dede:field name='typename'/}</h3>
            <pre>{dede:field name='description'/}······……...</pre>
            <a href="{dede:field name='typeurl'/}" class="lh-more gray"></a> </div>
        </div>
      </div>
    </div>