<?php
$z[0]=Array("field","",43,71);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",80,109);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",111,140);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",164,281);
$z[3][4]=array();
$z[3][4]['type']="son";

?>