<?php
$z[0]=Array("global","",167,187);
$z[0][4]=array();
$z[0][4]['name']="cfg_g";
$z[1]=Array("field","",193,222);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",262,294);
$z[2][4]=array();
$z[2][4]['name']="description";
$z[3]=Array("field","",502,531);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n            <li><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n            ",566,731);
$z[4][4]=array();
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";
$z[5]=Array("global","",829,851);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("field","",1079,1108);
$z[6][4]=array();
$z[6][4]['name']="typename";
$z[7]=Array("field","",1135,1163);
$z[7][4]=array();
$z[7][4]['name']="typeurl";
$z[8]=Array("arclist","\r\n			  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" class=\"iopo\"><img class=\"bpic\" src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a>\r\n                <div class=\"txt\">\r\n                  <h2>[field:title/]</h2>\r\n                  <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n                  <div class=\"lx\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" title=\"[field:title/]\" class=\"x1\">查看详情</a><a href=\"http://wpa.qq.com/msgrd?v=3&uin=88888888&site=qq&menu=yes\" title=\"立即咨询\" class=\"x2\">立即咨询</a></div>\r\n                </div>\r\n              </li>\r\n			  ",1291,1967);
$z[8][4]=array();
$z[8][4]['row']="10";
$z[8][4]['titlelen']="50";
$z[8][4]['orderby']="pubdate";
$z[9]=Array("arclist","\r\n				  <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/>\r\n                    <h2>[field:title/]<i class=\"icon\"></i></h2>\r\n                    </a></li>\r\n					",2189,2472);
$z[9][4]=array();
$z[9][4]['row']="10";
$z[9][4]['titlelen']="50";
$z[9][4]['orderby']="pubdate";

?>