<?php
$z[0]=Array("field","",105,133);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",210,241);
$z[1][4]=array();
$z[1][4]['name']="typenameen";
$z[2]=Array("field","",283,312);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("field","",358,386);
$z[3][4]=array();
$z[3][4]['name']="content";
$z[4]=Array("field","",415,443);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>