<div class="lh-profile honor clearfix" id="about10">
      <div class="img" style="background-image:url({dede:field name='typeimg'/});"></div>
      <div class="text">
        <div> <h2 class="lh-public-h2">{dede:field name='typenameen'/}</h2>
          <h3 class="lh-public-h3">{dede:field name='typename'/}</h3>
          <pre class="lh-public-pre">
{dede:field name='content'/}
</pre>
          <a href="{dede:field name='typeurl'/}" class="lh-look">查看更多</a> </div>
      </div>
    </div>