<?php
$z[0]=Array("field","",179,208);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("channel","<a class=\"item\" href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> ",402,544);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['noself']="yes";
$z[2]=Array("arclist","\r\n			<dd class=\"d[field:global.autoindex/]\">\r\n              <div class=\"box1\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">\r\n                <h3>[field:title/]</h3>\r\n                <p>[field:description function=\"cn_substr(@me,150)\"/]...</p>\r\n                <i class=\"icon\"></i><span class=\"icon\"></span></a></div>\r\n              <div class=\"box2\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a></div>\r\n            </dd>\r\n			",724,1282);
$z[2][4]=array();
$z[2][4]['limit']="0,2";
$z[2][4]['titlelen']="60";
$z[2][4]['orderby']="pubdate";

?>