<?php
$z[0]=Array("typelink","",23,40);
$z[0][4]=array();
$z[1]=Array("typenameen","",40,59);
$z[1][4]=array();
$z[2]=Array("global","\r\n                      \$a=\"\";\r\n                        \$b=\" class='on'\";\r\n                        if ((@me%0)==0 && @me!=0)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        ",60,315);
$z[2][4]=array();
$z[2][4]['runphp']="yes";
$z[2][4]['name']="autoindex";
$z[3]=Array("typename","",316,333);
$z[3][4]=array();

?>