<?php
$z[0]=Array("flink","[field:link /]     ",177,256);
$z[0][4]=array();
$z[0][4]['titlelen']="80";
$z[0][4]['row']="24";
$z[0][4]['type']="text";
$z[1]=Array("channel","<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a> ",471,612);
$z[1][4]=array();
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="";
$z[2]=Array("global","",976,998);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",1122,1144);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",1371,1397);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",1485,1509);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",1511,1535);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";
$z[7]=Array("global","",1977,1999);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";
$z[8]=Array("global","",2057,2078);
$z[8][4]=array();
$z[8][4]['name']="cfg_qq";
$z[9]=Array("global","",2287,2312);
$z[9][4]=array();
$z[9][4]['name']="cfg_weixin";

?>