<?php
$z[0]=Array("type","<li><a href=\"[field:typelink /][field:seotitle /]\"> <i class=\"iconfont icon-friends\"></i><em>[field:typename /]</em><span class=\"iconfont icon-xiangyou\"></span> </a></li>",361,566);
$z[0][4]=array();
$z[0][4]['typeid']="39";
$z[1]=Array("type","<li><a href=\"[field:typelink /]\"> <i class=\"iconfont icon-icon_feedback\"></i><em>[field:typename /]</em><span class=\"iconfont icon-xiangyou\"></span> </a></li>",584,777);
$z[1][4]=array();
$z[1][4]['typeid']="40";
$z[2]=Array("type","<li><a href=\"[field:typelink /][field:seotitle /]\"> <i class=\"iconfont icon-location\"></i><em>[field:typename /]</em><span class=\"iconfont icon-xiangyou\"></span> </a></li>",795,1001);
$z[2][4]=array();
$z[2][4]['typeid']="41";
$z[3]=Array("global","",1216,1240);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",1276,1298);
$z[4][4]=array();
$z[4][4]['name']="cfg_add";
$z[5]=Array("global","",1334,1356);
$z[5][4]=array();
$z[5][4]['name']="cfg_fax";
$z[6]=Array("global","",1366,1388);
$z[6][4]=array();
$z[6][4]['name']="cfg_tel";
$z[7]=Array("global","",1424,1448);
$z[7][4]=array();
$z[7][4]['name']="cfg_email";
$z[8]=Array("global","",1577,1603);
$z[8][4]=array();
$z[8][4]['name']="cfg_powerby";
$z[9]=Array("global","",1680,1704);
$z[9][4]=array();
$z[9][4]['name']="cfg_beian";
$z[10]=Array("flink","[field:link /] 丨 ",1732,1811);
$z[10][4]=array();
$z[10][4]['titlelen']="80";
$z[10][4]['row']="24";
$z[10][4]['type']="text";

?>