<?php
$z[0]=Array("global","",106,132);
$z[0][4]=array();
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("global","",211,235);
$z[1][4]=array();
$z[1][4]['name']="cfg_beian";
$z[2]=Array("global","",237,261);
$z[2][4]=array();
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",460,482);
$z[3][4]=array();
$z[3][4]['name']="cfg_tel";
$z[4]=Array("global","",540,561);
$z[4][4]=array();
$z[4][4]['name']="cfg_qq";

?>