<?php
$z[0]=Array("global","",101,122);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("global","",653,679);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",719,745);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","(@me==\"\")? @me=\"class='hover'\":@me=\"\";",918,1006);
$z[3][4]=array();
$z[3][4]['name']="typeid";
$z[3][4]['runphp']="yes";
$z[4]=Array("channelartlist","<li><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\" class=\"{dede:field.currentstyle/}\">\r\n          <p>{dede:field name='typename'/}</p>\r\n          <i></i></a>\r\n          <dl>\r\n            {dede:channel type='son' noself='yes'}\r\n            <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n            {/dede:channel}            \r\n          </dl>\r\n        </li>",1076,1587);
$z[4][4]=array();
$z[4][4]['row']="7";
$z[4][4]['typeid']="top";
$z[4][4]['currentstyle']="hover";
$z[5]=Array("global","",1800,1822);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";

?>