<?php
$z[0]=Array("channel","<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>[field:global runphp='yes' name=autoindex]if(@me%8==1){\r\n														@me='';\r\n													}else if(@me%8==2){\r\n														@me='';\r\n													}else if(@me%8==3){@me='\r\n	<li class=\"lh-logo\"><a href=\"/\"><img src=\"/skin/images/logo.png\"/></a></li>\r\n	';\r\n													}else if(@me%8==4){\r\n														@me='';\r\n													}else if(@me%8==5){\r\n														@me='';\r\n													}else if(@me%8==6){\r\n														@me='';\r\n													}else if(@me%8==7){\r\n														@me='';\r\n													}else{\r\n														@me='';\r\n													}[/field:global]",109,791);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['row']="8";
$z[0][4]['currentstyle']="";
$z[1]=Array("channelartlist","<li>\r\n          <dl>\r\n            <dt><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></dt>\r\n            {dede:channel type='son' noself='yes'}\r\n            <dd><a href=\"[field:typelink/]\">[field:typename/]</a></dd>\r\n            {/dede:channel}            \r\n          </dl>\r\n        </li>",1245,1643);
$z[1][4]=array();
$z[1][4]['row']="12";
$z[1][4]['typeid']="top";
$z[1][4]['currentstyle']="hover";

?>