<?php
$z[0]=Array("global","",104,125);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type","<a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a>",187,300);
$z[1][4]=array();
$z[1][4]['typeid']="13";
$z[2]=Array("type","<a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a>",322,435);
$z[2][4]=array();
$z[2][4]['typeid']="14";
$z[3]=Array("global","",637,663);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",757,783);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",941,963);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("field","(@me==\"\")? @me=\" hover\":@me=\"\";",1196,1277);
$z[6][4]=array();
$z[6][4]['name']="typeid";
$z[6][4]['runphp']="yes";
$z[7]=Array("channelartlist","<li class=\"item\"><a class=\"hvr-underline-from-center1 {dede:field.currentstyle/}\" href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n          <div class=\"suNav\">  {dede:channel type='son' noself='yes'}<a class=\"subA\" href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>  {/dede:channel}</div>\r\n        </li>",1310,1781);
$z[7][4]=array();
$z[7][4]['row']="7";
$z[7][4]['typeid']="top";
$z[7][4]['currentstyle']="hover";

?>