<?php
$z[0]=Array("global","",101,122);
$z[0][4]=array();
$z[0][4]['name']="cfg_gg";
$z[1]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",245,367);
$z[1][4]=array();
$z[1][4]['typeid']="13";
$z[2]=Array("type","<li><a href=\"[field:typelink /]\" title=\"[field:typename /]\">[field:typename /]</a></li>",388,510);
$z[2][4]=array();
$z[2][4]['typeid']="14";
$z[3]=Array("global","",751,777);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",817,843);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("field","(@me==\"\")? @me=\"class='hover'\":@me=\"\";",1016,1104);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['runphp']="yes";
$z[6]=Array("channelartlist","<li><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\" class=\"{dede:field.currentstyle/}\">\r\n          <p>{dede:field name='typename'/}</p>\r\n          <i></i></a>\r\n          <dl>\r\n            {dede:channel type='son' noself='yes'}\r\n            <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n            {/dede:channel}            \r\n          </dl>\r\n        </li>",1174,1685);
$z[6][4]=array();
$z[6][4]['row']="7";
$z[6][4]['typeid']="top";
$z[6][4]['currentstyle']="hover";
$z[7]=Array("global","",1898,1920);
$z[7][4]=array();
$z[7][4]['name']="cfg_tel";

?>