<?php
$z[0]=Array("global","",254,280);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",324,354);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",391,418);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",2020,2055);
$z[3][4]=array();
$z[3][4]['filename']="head.htm";
$z[4]=Array("myppt","<div><a href=\"[field:url/]\"><img src=\"[field:pic/]\" alt=\"[field:title/]\"/></a></div>",2172,2292);
$z[4][4]=array();
$z[4][4]['typeid']="2";
$z[5]=Array("hotwords","",2680,2728);
$z[5][4]=array();
$z[5][4]['num']="6";
$z[5][4]['subday']="365";
$z[5][4]['maxlength']="16";
$z[6]=Array("include","",20338,20375);
$z[6][4]=array();
$z[6][4]['filename']="footer.htm";

?>