<?php
$z[0]=Array("global","",308,334);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",387,417);
$z[1][4]=array();
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",454,481);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",868,907);
$z[3][4]=array();
$z[3][4]['filename']="header_m.htm";
$z[4]=Array("channel","\r\n    <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">\r\n      <h3>[field:typename/]</h3>\r\n      </a></li>\r\n    ",1067,1243);
$z[4][4]=array();
$z[4][4]['type']="top";
$z[4][4]['row']="7";
$z[5]=Array("myppt","<li class=\"item\"><a href=\"[field:url/]\"><img src=\"[field:pic/]\" alt=\"[field:title/]\"></a></li>",1427,1557);
$z[5][4]=array();
$z[5][4]['typeid']="3";
$z[6]=Array("include","",16761,16800);
$z[6][4]=array();
$z[6][4]['filename']="footer_m.htm";

?>