<?php
$z[0]=Array("field","",763,782);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",783,809);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",850,879);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",919,977);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1231,1266);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        ",1541,1738);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[6]=Array("list","<li><a href=\"[field:arcurl/]\">\r\n          <div class=\"img\"><img src=\"[field:litpic/]\"/></div>\r\n          <h2>[field:title/]</h2>\r\n          </a> </li>",2343,2530);
$z[6][4]=array();
$z[6][4]['pagesize']="9";
$z[7]=Array("pagelist","",2618,2684);
$z[7][4]=array();
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2761,2798);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>