<?php
$z[0]=Array("field","",763,782);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",783,809);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",850,879);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",919,977);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1255,1290);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\"[field:global runphp='yes' name=autoindex]\r\n                      \$a=\"\";\r\n                        \$b=\" class='on'\";\r\n                        if ((@me%0)==0 && @me!=0)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        [/field:global]>[field:typename/]</a></li>\r\n        ",1565,1966);
$z[5][4]=array();
$z[5][4]['type']="son";
$z[5][4]['typeid']="25";
$z[5][4]['currentstyle']="";
$z[6]=Array("channel","<dd><a href='[field:typelink/]'>\r\n        <div class='img'><img src='[field:typeimg/]'/></div>\r\n        <h2>[field:typename/]</h2>\r\n        </a></dd>",2049,2254);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="";
$z[7]=Array("list","<li><a href=\"[field:arcurl/]\">\r\n          <div class=\"img\"><img src=\"[field:litpic/]\"/></div>\r\n          <h2>[field:title/]</h2>\r\n          </a></li>",2843,3031);
$z[7][4]=array();
$z[7][4]['pagesize']="999";
$z[8]=Array("include","",3098,3135);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>