<?php
$z[0]=Array("field","",763,782);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",783,809);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",850,879);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",919,977);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1231,1266);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1496,1554);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n        ",1793,1990);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='on'>~typename~</a></li>";
$z[7]=Array("channel","\r\n      <li>\r\n        <div class=\"img\" style=\"background-image:url([field:typeimg/]);\"></div>\r\n        <div class=\"text wow animated fadeInUp\">\r\n          <div>\r\n            <h2 class=\"lh-public-h2\">[field:typenameen/]</h2>\r\n            <h3 class=\"lh-public-h3\">[field:typename/]</h3>\r\n            <pre class=\"lh-public-pre\">[field:description/]...</pre>\r\n            <a href=\"[field:typelink/]\" class=\"lh-look\">查看更多</a> </div>\r\n        </div>\r\n      </li>\r\n      ",2089,2617);
$z[7][4]=array();
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="";
$z[8]=Array("include","",2676,2713);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>