<?php
$z[0]=Array("field","",254,273);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",274,300);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",341,370);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",410,468);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",840,875);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("channelartlist","<li class='{dede:field.currentstyle/}'><a class=\"nav1\" href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}<s></s></a>\r\n        <div class=\"subMenu clearfix\"> {dede:channel type='son' noself='yes'}<a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a>{/dede:channel} </div>\r\n      </li>",1113,1546);
$z[5][4]=array();
$z[5][4]['typeid']="5";
$z[5][4]['currentstyle']="hover";
$z[6]=Array("field","",1662,1691);
$z[6][4]=array();
$z[6][4]['name']="position";
$z[7]=Array("list","<li class=\"item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n        <h3>[field:title/]</h3>\r\n        <div class=\"bg\"><s class=\"icon\"></s></div>\r\n        </a></li>",1857,2112);
$z[7][4]=array();
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",2170,2236);
$z[8][4]=array();
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2294,2331);
$z[9][4]=array();
$z[9][4]['filename']="footer.htm";

?>