<?php
$z[0]=Array("field","",763,782);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",783,809);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",850,879);
$z[2][4]=array();
$z[2][4]['name']="keywords";
$z[3]=Array("field","",919,977);
$z[3][4]=array();
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1255,1290);
$z[4][4]=array();
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1517,1575);
$z[5][4]=array();
$z[5][4]['name']="typeid";
$z[5][4]['function']="GetTopTypename(@me)";
$z[6]=Array("channel","\r\n        <li><a href=\"/a/zoujinwomen/gongsijianjie/#about[field:global name=autoindex runphp=\"yes\"]@me=@me+9;[/field:global]\"[field:global runphp='yes' name=autoindex]\r\n                      \$a=\"\";\r\n                        \$b=\"class='on'\";\r\n                        if ((@me%1)==0 && @me!=1)  @me=\$a;\r\n                        else  @me=\$b;\r\n                        [/field:global]>[field:typename/]</a></li>\r\n        ",1834,2307);
$z[6][4]=array();
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="";
$z[7]=Array("list","<li class=\"wow animated zoomIn\"><a href=\"javascript:;\">\r\n          <div class=\"img\"><img layer-src=\"[field:litpic/]\" src=\"[field:litpic/]\" alt=\"[field:title/]\" /></div>\r\n          <h2>[field:title/]</h2>\r\n          </a> </li>",2484,2747);
$z[7][4]=array();
$z[7][4]['pagesize']="99";
$z[8]=Array("include","",2814,2851);
$z[8][4]=array();
$z[8][4]['filename']="footer.htm";

?>