<?php
$z[0]=Array("global","",266,292);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",745,780);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",1007,1062);
$z[2][4]=array();
$z[2][4]['name']="keyword";
$z[2][4]['function']="RemoveXSS(@me)";
$z[3]=Array("list","<li class=\"clearfix\" aos=\"fade-up\" aos-easing=\"ease\" aos-duration=\"700\" aos-delay=\"100\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><span class=\"fl box1\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></span><span class=\"fl box2\">\r\n        <h1>[field:title/]</h1>\r\n        <p>[field:description function=\"cn_substr(@me,200)\"/]...</p>\r\n        <span>阅读量：[field:click/]</span></span><span class=\"right\">\r\n        <h3>[field:pubdate function=\"MyDate('m-d',@me)\"/]</h3>\r\n        <p>[field:pubdate function=\"MyDate('Y',@me)\"/]</p>\r\n        </span></a></li>",1190,1792);
$z[3][4]=array();
$z[3][4]['pagesize']="5";
$z[4]=Array("pagelist","",1854,1920);
$z[4][4]=array();
$z[4][4]['listitem']="index,end,pre,next,pageno";
$z[4][4]['listsize']="1";
$z[5]=Array("include","",1978,2015);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>