<?php
$z[0]=Array("global","",267,293);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",746,781);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("global","",1147,1173);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("global","",1204,1230);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("channelartlist","\r\n      <dl class=\"sitemap\">\r\n        <dt><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></dt>\r\n        <dd> {dede:channel type ='son'} <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </dd>\r\n      </dl>\r\n      ",1422,1794);
$z[4][4]=array();
$z[4][4]['typeid']="all";
$z[5]=Array("include","",1869,1906);
$z[5][4]=array();
$z[5][4]['filename']="footer.htm";

?>