<?php
$z[0]=Array("global","",267,293);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",746,781);
$z[1][4]=array();
$z[1][4]['filename']="head.htm";
$z[2]=Array("channelartlist","\r\n      <dl class=\"sitemap\">\r\n        <dt><a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a></dt>\r\n        <dd> {dede:channel type ='son'} <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> {/dede:channel} </dd>\r\n      </dl>\r\n      ",1239,1611);
$z[2][4]=array();
$z[2][4]['typeid']="all";
$z[3]=Array("include","",1686,1723);
$z[3][4]=array();
$z[3][4]['filename']="footer.htm";

?>